### PR TITLE
feat(cocoapods): cocoapods 1.12.0 compatibility

### PR DESCRIPTION
**Pull request by crherman7**
Fixes https://github.com/doublesymmetry/cocoapods-patch/issues/25.

The function signature for `clean_pod`, https://github.com/CocoaPods/CocoaPods/blob/df6cd9e0c51c54490be617a655fca80817c8b9b1/lib/cocoapods/sandbox.rb#L93, has changed to require the pod directory which has been abstracted from the `clean_pod` function to `pod_dir` https://github.com/CocoaPods/CocoaPods/blob/df6cd9e0c51c54490be617a655fca80817c8b9b1/lib/cocoapods/sandbox.rb#L182, which we can use instead.

### CODE REVIEW

**Comment by jimmyeisenhauer** [comment]
Would love to see this released!

**Comment by jeffmon** [comment]
I would love to see this merged in as well!

@crherman7 Thank you for this PR, I was able to add your fork/branch to my Gemfile like so:

```
gem 'cocoapods-patch', git: 'https://github.com/crherman7/cocoapods-patch.git', branch: 'feat/cocoapods_1.12.0'
```

..but I'm still running into this error when trying to `pod install`:

```
Error loading plugin file `/Users/x/.gem/gems/cocoapods-patch-1.0.2/lib/cocoapods_plugin.rb`.

Gem::ConflictError - Unable to activate cocoapods-patch-1.0.2, because cocoapods-1.12.0 conflicts with cocoapods (~> 1.11.0)
```

Do you know why that's happening? Thanks!

**Comment by crherman7** [comment]
> I would love to see this merged in as well!
> 
> 
> 
> @crherman7 Thank you for this PR, I was able to add your fork/branch to my Gemfile like so:
> 
> 
> 
> ```
> 
> gem 'cocoapods-patch', git: 'https://github.com/crherman7/cocoapods-patch.git', branch: 'feat/cocoapods_1.12.0'
> 
> ```
> 
> 
> 
> ..but I'm still running into this error when trying to `pod install`:
> 
> 
> 
> ```
> 
> Error loading plugin file `/Users/x/.gem/gems/cocoapods-patch-1.0.2/lib/cocoapods_plugin.rb`.
> 
> 
> 
> Gem::ConflictError - Unable to activate cocoapods-patch-1.0.2, because cocoapods-1.12.0 conflicts with cocoapods (~> 1.11.0)
> 
> ```
> 
> 
> 
> Do you know why that's happening? Thanks!

Based on the error message it looks like it's still trying to use cocoapods-patch 1.0.2. Can you list out your gems and ensure 1.0.2 is uninstalled and 1.0.3 is installed. 

Otherwise I can take a deeper look tomorrow!

**Comment by jeffmon** [comment]
> Based on the error message it looks like it's still trying to use cocoapods-patch 1.0.2. Can you list out your gems and ensure 1.0.2 is uninstalled and 1.0.3 is installed.

Thanks for the response! After running `bundle install` to list the gems, it did show `cocoapods-patch 1.0.2`, so I commented out `Gemfile`, ran `bundle clean` to clear out the gems, restored `Gemfile`, and ran `bundle install` again. Unfortunately, it's still showing that same error. When I run `gem query --local`, I see this:

```
...
cocoapods (1.12.0, 1.11.3, 1.10.2)
cocoapods-core (1.12.0, 1.11.3, 1.10.2)
cocoapods-deintegrate (1.0.5)
cocoapods-downloader (1.6.3, 1.6.1)
cocoapods-patch (1.0.2)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.1)
cocoapods-trunk (1.6.0)
...
```

**Comment by crherman7** [comment]
@jeffmon any chance you have mixed installs i.e. one with brew and one with gem?

**Comment by jeffmon** [comment]
> any chance you have mixed installs i.e. one with brew and one with gem? I know you used bundle - just trying to think of any other edge cases.

Thanks for the suggestion, after checking the brew list, that doesn't seem to be the case. Thanks again for your help! I'll eventually figure this out, and comment on my solution if I get there.

**Comment by crherman7** [comment]
@jeffmon absolutely - I want to get this released, so making sure this works for all is important!

Can you try one last thing.....instead of using gemfile can you just locally bundle the gem and install it and see if it works? I want to narrow everything out.

**Comment by jimmyeisenhauer** [comment]
Is this project still being maintained?  Curious if anyone has heard from any of the owners on the chance to get this fix released?  Needing to make decision if we quit using it or not here real soon.

**Comment by lockieluke** [comment]
MERGEEEE

**Comment by efstathiosntonas** [comment]
just leaving this here, `specific_install` command: 

`gem specific_install 'https://github.com/crherman7/cocoapods-patch.git' -b 'feat/cocoapods_1.12.0'`

**Comment by babzcraig** [comment]
Hi @dcvz any update on this? this would be super valuable for some upgrades we're working on at the moment.

**Pull request merged**
